// <auto-generated />
using DDDInPractice.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DDDInPractice.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20200730110352_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DDDInPractice.Domains.Slot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("SlotId")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Position")
                        .HasColumnName("Position")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Price")
                        .HasColumnName("Price")
                        .HasColumnType("int");

                    b.Property<int>("ProductCount")
                        .HasColumnName("ProductCount")
                        .HasColumnType("int");

                    b.Property<string>("ProductName")
                        .HasColumnName("ProductName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VendingMachineId")
                        .HasColumnName("VendingMachineId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VendingMachineId");

                    b.ToTable("Slots");
                });

            modelBuilder.Entity("DDDInPractice.Domains.VendingMachine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("MachineId")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("IsInTransaction")
                        .HasColumnName("IsInTransaction")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("VendingMachines");
                });

            modelBuilder.Entity("DDDInPractice.Domains.Slot", b =>
                {
                    b.HasOne("DDDInPractice.Domains.VendingMachine", "VendingMachine")
                        .WithMany("Slots")
                        .HasForeignKey("VendingMachineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DDDInPractice.Domains.VendingMachine", b =>
                {
                    b.OwnsOne("DDDInPractice.Domains.Money", "MachineMoney", b1 =>
                        {
                            b1.Property<int>("VendingMachineId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<int>("Fifty")
                                .HasColumnName("AmountOf50K")
                                .HasColumnType("int");

                            b1.Property<int>("Five")
                                .HasColumnName("AmountOf5K")
                                .HasColumnType("int");

                            b1.Property<int>("FiveHundred")
                                .HasColumnName("AmountOf500K")
                                .HasColumnType("int");

                            b1.Property<int>("OneHundred")
                                .HasColumnName("AmountOf100K")
                                .HasColumnType("int");

                            b1.Property<int>("Ten")
                                .HasColumnName("AmountOf10K")
                                .HasColumnType("int");

                            b1.Property<int>("Twenty")
                                .HasColumnName("AmountOf20K")
                                .HasColumnType("int");

                            b1.Property<int>("TwoHundred")
                                .HasColumnName("AmountOf200K")
                                .HasColumnType("int");

                            b1.HasKey("VendingMachineId");

                            b1.ToTable("VendingMachines");

                            b1.WithOwner()
                                .HasForeignKey("VendingMachineId");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
